"""ListaSugestoes model — daily visit suggestion list generated by morning batch.

See docs/architecture/decisoes_design.md G9 (list size), G8 (ordering),
G6 (idempotency via UNIQUE constraint).
"""

import uuid
from datetime import date

from sqlalchemy import ForeignKey, Index, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDMixin


class ListaSugestoes(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "lista_sugestoes"

    profissional_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("profissionais.id"))
    crianca_ref: Mapped[uuid.UUID] = mapped_column(ForeignKey("criancas.id"))
    data_sugestao: Mapped[date]

    # Status lifecycle: SUGERIDA -> VISITADA | NAO_VISITADA
    status: Mapped[str] = mapped_column(default="SUGERIDA")

    # Positioning and scoring
    posicao_lista: Mapped[int | None]
    score: Mapped[int] = mapped_column(default=0)
    grupo_risco: Mapped[bool] = mapped_column(default=False)
    override_topo: Mapped[bool] = mapped_column(default=False)

    # Rich data for display
    motivos: Mapped[list | None] = mapped_column(JSONB)
    mensagem_formatada: Mapped[str | None]

    __table_args__ = (
        # Idempotency: one suggestion per (profissional, crianca, day)
        UniqueConstraint(
            "profissional_id",
            "crianca_ref",
            "data_sugestao",
            name="uq_lista_sugestoes_profissional_crianca_data",
        ),
        # Efficient daily list retrieval
        Index(
            "ix_lista_sugestoes_profissional_data_status",
            "profissional_id",
            "data_sugestao",
            "status",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<ListaSugestoes id={self.id} profissional={self.profissional_id}"
            f" crianca={self.crianca_ref} data={self.data_sugestao} status={self.status!r}>"
        )
